### ISSUE TITLE
Want to be helped

### ISSUE THREAD

**Issue by AdvanceLv** [YLiu-5/Random_Field_Generation#1]

**Comment by YLiu-5** [comment]
Hi,

Sorry for the late reply. Do you mean generating two correlated **random fields** simultaneously? In that case, you could assemble a 2N by 2N covariance matrix first (suppose each random field has N degrees of freedom). Then try to apply the KL expansion method.

**Comment by AdvanceLv** [comment]
好的！谢谢啦。
我刚接触随机场，研究研究☺️



---- Replied Message ----
| From | ***@***.***> |
| Date | 03/28/2023 18:56 |
| To | ***@***.***> |
| Cc | Lv ***@***.***>***@***.***> |
| Subject | Re: [YLiu-5/Random_Field_Generation] Want to be helped (Issue #1) |

Hi,

Sorry for the late reply. Do you mean generating two correlated random fields simultaneously? In that case, you could assemble a 2N by 2N covariance matrix first (suppose each random field has N degrees of freedom). Then try to apply the KL expansion method.
